### ISSUE TITLE
Fails with import error

### ISSUE THREAD

**Issue by Dunedan** [Lucas-C/pre-commit-hooks-safety#2]
When trying to use this check I get the following error message:
```
Python dependencies checker...........................................................................................................................................................................................................Failed
hookid: python-safety-dependencies-check

Traceback (most recent call last):
  File "/home/user/.pre-commit/repoR_abcd/py_env-default/bin/safety", line 11, in <module>
    load_entry_point('pre-commit-hooks-safety==1.0.0', 'console_scripts', 'safety')()
  File "/home/user/.pre-commit/repoR_abcd/py_env-default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/.pre-commit/repoR_abcd/py_env-default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "/home/user/.pre-commit/repoR_abcd/py_env-default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2268, in load
    return self.resolve()
  File "/home/user/.pre-commit/repoR_abcd/py_env-default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/.pre-commit/repoR_abcd/py_env-default/local/lib/python2.7/site-packages/pre_commit_hooks/safety.py", line 3, in <module>
    from safety.cli import check
ImportError: No module named cli
```

The configuration in `pre-commit-config.yaml` is:
```yaml
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.0.9
    hooks:
    -   id: python-safety-dependencies-check
```

When I rename your `safety.py` to something else (like `safety_check.py`) and adjust `setup.py` accordingly it works, so I'd say it's a naming collision between your `safety.py` and `safety` itself.

The same happens for me with your `bandit` check as well.

**Comment by Lucas-C** [comment]
Thanks for the report !
I fixed this in 1.0.10
Can you try it ?

**Comment by Dunedan** [comment]
Works now for me. :+1:
Do you mind fixing the bandit check as well?

**Comment by Lucas-C** [comment]
It looks ok: https://travis-ci.org/Lucas-C/pre-commit-hooks-bandit

**Comment by Dunedan** [comment]
Still having issues with the bandit check, but I'll open an issue there once I had another look what's the problem there.
Thanks for the quick fix of the safety check.
